image: atlassian/default-image:2

pipelines:
  default:
      - step:
          name: build
          image: python:2.7
          script:
            - pip --quiet install -r requirements.txt -t lib/
            - echo "key = '${GOOGLE_API_KEY}'" > api_key.py
            - python test_main.py
          artifacts:
            - lib/**
            - api_key.py
      - step:
          name: deploy
          image: google/cloud-sdk
          deployment: production
          script:
            - echo "$GOOGLE_CLIENT_SECRET" > /tmp/gae_key.json
            - gcloud config set project $GAE_PROJECT
            - gcloud auth activate-service-account --key-file /tmp/gae_key.json
            - gcloud --quiet --verbosity=error app deploy app.yaml --promote
            - rm /tmp/gae_key.json
      - step:
          name: test
          image: python:2.7
          script:
            - python e2e_test.py
